## Practice Exercise 2

In this assignment, you will try to find some interesting insights into a few movies released between 1916 and 2016, using Python. You will have to download a movie dataset, write Python code to explore the data, gain insights into the movies, actors, directors, and collections, and submit the code.

#### Some tips before starting the assignment

1. Identify the task to be performed correctly, and only then proceed to write the required code. Don’t perform any incorrect analysis or look for information that isn’t required for the assignment.
2. In some cases, the variable names have already been assigned, and you just need to write code against them. In other cases, the names to be given are mentioned in the instructions. We strongly advise you to use the mentioned names only.
3. Always keep inspecting your data frame after you have performed a particular set of operations.
4. There are some checkpoints given in the IPython notebook provided. They're just useful pieces of information you can use to check if the result you have obtained after performing a particular task is correct or not.
5. Note that you will be asked to refer to documentation for solving some of the questions. That is done on purpose for you to learn new commands and also how to use the documentation.

In [1]:
# Import the numpy and pandas packages

import numpy as np
import pandas as pd

### Task 1: Reading and Inspection

**Subtask 1.1: Import and read**

Import and read the movie database. Store it in a variable called `movies`.

In [4]:
# Write your code for importing the csv file here
movies = pd.read_csv("Movies.csv", header = 0)
movies

,color,director_name,num_critic_for_reviews,duration,director_facebook_likes,actor_3_facebook_likes,actor_2_name,actor_1_facebook_likes,gross,genres,...,num_user_for_reviews,language,country,content_rating,budget,title_year,actor_2_facebook_likes,imdb_score,aspect_ratio,movie_facebook_likes
0,Color,James Cameron,723.0,178.0,0.0,855.0,Joel David Moore,1000.0,760505847.0,Action|Adventure|Fantasy|Sci-Fi,...,3054.0,English,USA,PG-13,237000000.0,2009.0,936.0,7.9,1.78,33000
1,Color,Gore Verbinski,302.0,169.0,563.0,1000.0,Orlando Bloom,40000.0,309404152.0,Action|Adventure|Fantasy,...,1238.0,English,USA,PG-13,300000000.0,2007.0,5000.0,7.1,2.35,0
2,Color,Sam Mendes,602.0,148.0,0.0,161.0,Rory Kinnear,11000.0,200074175.0,Action|Adventure|Thriller,...,994.0,English,UK,PG-13,245000000.0,2015.0,393.0,6.8,2.35,85000
3,Color,Christopher Nolan,813.0,164.0,22000.0,23000.0,Christian Bale,27000.0,448130642.0,Action|Thriller,...,2701.0,English,USA,PG-13,250000000.0,2012.0,23000.0,8.5,2.35,164000
4,Color,Andrew Stanton,462.0,132.0,475.0,530.0,Samantha Morton,640.0,73058679.0,Action|Adventure|Sci-Fi,...,738.0,English,USA,PG-13,263700000.0,2012.0,632.0,6.6,2.35,24000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3848,Color,Shane Carruth,143.0,77.0,291.0,8.0,David Sullivan,291.0,424760.0,Drama|Sci-Fi|Thriller,...,371.0,English,USA,PG-13,7000.0,2004.0,45.0,7.0,1.85,19000
3849,Color,Neill Dela Llana,35.0,80.0,0.0,0.0,Edgar Tancangco,0.0,70071.0,Thriller,...,35.0,English,Philippines,Not Rated,7000.0,2005.0,0.0,6.3,NaN,74
3850,Color,Robert Rodriguez,56.0,81.0,0.0,6.0,Peter Marquardt,121.0,2040920.0,Action|Crime|Drama|Romance|Thriller,...,130.0,Spanish,USA,R,7000.0,1992.0,20.0,6.9,1.37,0
3851,Color,Edward Burns,14.0,95.0,0.0,133.0,Caitlin FitzGerald,296.0,4584.0,Comedy|Drama,...,14.0,English,USA,Not Rated,9000.0,2011.0,205.0,6.4,NaN,413
3852,Color,Jon Gunn,43.0,90.0,16.0,16.0,Brian Herzlinger,86.0,85222.0,Documentary,...,84.0,English,USA,PG,1100.0,2004.0,23.0,6.6,1.85,456

**Subtask 1.2: Inspect the dataframe**

Inspect the dataframe's columns, shapes, variable types etc.

#### <font color='red'>Question 1: How many rows and columns are present in the dataframe? </font>
-  <font color='red'>(3821, 26)</font>
-  <font color='red'>(3879, 28)</font>
-  <font color='red'>(3853, 28)</font>
-  <font color='red'>(3866, 26)</font>

In [6]:
# Write your code for inspection here
movies.shape

(3853, 28)

#### <font color='red'>Question 2: How many columns have null values present in them? Try writing a code for this instead of counting them manually.</font>

-  <font color='red'>3</font>
-  <font color='red'>6</font>
-  <font color='red'>9</font>
-  <font color='red'>12</font>

In [8]:
movies.isnull().any().sum()

12

### Task 2: Cleaning the Data

**Subtask 2.1: Drop unecessary columns**

For this assignment, you will mostly be analyzing the movies with respect to the ratings, gross collection, popularity of movies, etc. So many of the columns in this dataframe are not required. So it is advised to drop the following columns.
-  color
-  director_facebook_likes
-  actor_1_facebook_likes
-  actor_2_facebook_likes
-  actor_3_facebook_likes
-  actor_2_name
-  cast_total_facebook_likes
-  actor_3_name
-  duration
-  facenumber_in_poster
-  content_rating
-  country
-  movie_imdb_link
-  aspect_ratio
-  plot_keywords

In [9]:
# Check the 'drop' function in the Pandas library - dataframe.drop(list_of_unnecessary_columns, axis = )
# Write your code for dropping the columns here. It is advised to keep inspecting the dataframe after each set of operations
columns_to_drop = [
    "color", "director_facebook_likes", "actor_1_facebook_likes", 
    "actor_2_facebook_likes", "actor_3_facebook_likes", "actor_2_name", 
    "cast_total_facebook_likes", "actor_3_name", "duration", 
    "facenumber_in_poster", "content_rating", "country", 
    "movie_imdb_link", "aspect_ratio", "plot_keywords"
]

# Creating a new DataFrame without the specified columns
new_movies = movies.drop(columns=columns_to_drop)

#### <font color='red'>Question 3: What is the count of columns in the new dataframe? </font>
-  <font color='red'>10</font>
-  <font color='red'>13</font>
-  <font color='red'>15</font>
-  <font color='red'>17</font>

In [10]:
new_movies.shape

(3853, 13)

In [11]:
new_movies.head()

,director_name,num_critic_for_reviews,gross,genres,actor_1_name,movie_title,num_voted_users,num_user_for_reviews,language,budget,title_year,imdb_score,movie_facebook_likes
0,James Cameron,723.0,760505847.0,Action|Adventure|Fantasy|Sci-Fi,CCH Pounder,Avatar,886204,3054.0,English,237000000.0,2009.0,7.9,33000
1,Gore Verbinski,302.0,309404152.0,Action|Adventure|Fantasy,Johnny Depp,Pirates of the Caribbean: At World's End,471220,1238.0,English,300000000.0,2007.0,7.1,0
2,Sam Mendes,602.0,200074175.0,Action|Adventure|Thriller,Christoph Waltz,Spectre,275868,994.0,English,245000000.0,2015.0,6.8,85000
3,Christopher Nolan,813.0,448130642.0,Action|Thriller,Tom Hardy,The Dark Knight Rises,1144337,2701.0,English,250000000.0,2012.0,8.5,164000
4,Andrew Stanton,462.0,73058679.0,Action|Adventure|Sci-Fi,Daryl Sabara,John Carter,212204,738.0,English,263700000.0,2012.0,6.6,24000

**Subtask 2.2: Inspect Null values**

As you have seen above, there are null values in multiple columns of the new dataframe of 'movies'. Find out the percentage of null values in each column of the new dataframe of 'movies'.

#### <font color='red'>Question 4: Which column has the highest percentage of null values? </font>
-  <font color='red'>language</font>
-  <font color='red'>genres</font>
-  <font color='red'>num_critic_for_reviews</font>
-  <font color='red'>imdb_score</font>

In [15]:
# Write you code here
# Calculate the percentage of null values for each column
null_percentages = (new_movies.isnull().sum() / len(new_movies)) * 100
# sort it
null_percentages_sorted = null_percentages.sort_values(ascending=False)

# Print the result
print(null_percentages_sorted)

language                  0.103815
num_critic_for_reviews    0.025954
director_name             0.000000
gross                     0.000000
genres                    0.000000
actor_1_name              0.000000
movie_title               0.000000
num_voted_users           0.000000
num_user_for_reviews      0.000000
budget                    0.000000
title_year                0.000000
imdb_score                0.000000
movie_facebook_likes      0.000000
dtype: float64

**Subtask 2.3: Fill NaN values**

You might notice that the `language` column has some NaN values. Here, on inspection, you will see that it is safe to replace all the missing values with `'English'`.

In [16]:
# Write your code for filling the NaN values in the 'language' column here
new_movies["language"] = new_movies["language"].fillna("English")

#### <font color='red'>Question 5: What is the count of movies made in English language after replacing the NaN values with English? </font>
-  <font color='red'>3670</font>
-  <font color='red'>3674</font>
-  <font color='red'>3668</font>
-  <font color='red'>3672</font>

In [23]:
new_movies_eng = new_movies[new_movies["language"] == "English" ]

len(new_movies_eng)

3675

In [24]:
movies.loc[pd.isnull(movies['language']), ['language']] = 'English'
(movies.language == 'English').sum()

3675

### Task 3: Data Analysis

**Subtask 3.1: Change the unit of columns**

Convert the unit of the `budget` and `gross` columns from `$` to `million $`.

In [25]:
# Write your code for unit conversion here
movies["budget"] = movies["budget"]/1000000

In [26]:
movies["gross"] = movies["gross"]/1000000

In [27]:
movies.head()

,color,director_name,num_critic_for_reviews,duration,director_facebook_likes,actor_3_facebook_likes,actor_2_name,actor_1_facebook_likes,gross,genres,...,num_user_for_reviews,language,country,content_rating,budget,title_year,actor_2_facebook_likes,imdb_score,aspect_ratio,movie_facebook_likes
0,Color,James Cameron,723.0,178.0,0.0,855.0,Joel David Moore,1000.0,760.505847,Action|Adventure|Fantasy|Sci-Fi,...,3054.0,English,USA,PG-13,237.0,2009.0,936.0,7.9,1.78,33000
1,Color,Gore Verbinski,302.0,169.0,563.0,1000.0,Orlando Bloom,40000.0,309.404152,Action|Adventure|Fantasy,...,1238.0,English,USA,PG-13,300.0,2007.0,5000.0,7.1,2.35,0
2,Color,Sam Mendes,602.0,148.0,0.0,161.0,Rory Kinnear,11000.0,200.074175,Action|Adventure|Thriller,...,994.0,English,UK,PG-13,245.0,2015.0,393.0,6.8,2.35,85000
3,Color,Christopher Nolan,813.0,164.0,22000.0,23000.0,Christian Bale,27000.0,448.130642,Action|Thriller,...,2701.0,English,USA,PG-13,250.0,2012.0,23000.0,8.5,2.35,164000
4,Color,Andrew Stanton,462.0,132.0,475.0,530.0,Samantha Morton,640.0,73.058679,Action|Adventure|Sci-Fi,...,738.0,English,USA,PG-13,263.7,2012.0,632.0,6.6,2.35,24000

**Subtask 3.2: Find the movies with highest profit**

   1. Create a new column called `profit` which contains the difference of the two columns: `gross` and `budget`.
   2. Sort the dataframe using the `profit` column as reference. (Find which command can be used here to sort entries from the documentation)
   3. Extract the top ten profiting movies in descending order and store them in a new dataframe - `top10`

In [28]:
# Write your code for creating the profit column here
movies["profit"] = movies["gross"] - movies["budget"]

In [29]:
movies.head()

,color,director_name,num_critic_for_reviews,duration,director_facebook_likes,actor_3_facebook_likes,actor_2_name,actor_1_facebook_likes,gross,genres,...,language,country,content_rating,budget,title_year,actor_2_facebook_likes,imdb_score,aspect_ratio,movie_facebook_likes,profit
0,Color,James Cameron,723.0,178.0,0.0,855.0,Joel David Moore,1000.0,760.505847,Action|Adventure|Fantasy|Sci-Fi,...,English,USA,PG-13,237.0,2009.0,936.0,7.9,1.78,33000,523.505847
1,Color,Gore Verbinski,302.0,169.0,563.0,1000.0,Orlando Bloom,40000.0,309.404152,Action|Adventure|Fantasy,...,English,USA,PG-13,300.0,2007.0,5000.0,7.1,2.35,0,9.404152
2,Color,Sam Mendes,602.0,148.0,0.0,161.0,Rory Kinnear,11000.0,200.074175,Action|Adventure|Thriller,...,English,UK,PG-13,245.0,2015.0,393.0,6.8,2.35,85000,-44.925825
3,Color,Christopher Nolan,813.0,164.0,22000.0,23000.0,Christian Bale,27000.0,448.130642,Action|Thriller,...,English,USA,PG-13,250.0,2012.0,23000.0,8.5,2.35,164000,198.130642
4,Color,Andrew Stanton,462.0,132.0,475.0,530.0,Samantha Morton,640.0,73.058679,Action|Adventure|Sci-Fi,...,English,USA,PG-13,263.7,2012.0,632.0,6.6,2.35,24000,-190.641321

In [32]:
print(movies.columns)

Index(['color', 'director_name', 'num_critic_for_reviews', 'duration',
       'director_facebook_likes', 'actor_3_facebook_likes', 'actor_2_name',
       'actor_1_facebook_likes', 'gross', 'genres', 'actor_1_name',
       'movie_title', 'num_voted_users', 'cast_total_facebook_likes',
       'actor_3_name', 'facenumber_in_poster', 'plot_keywords',
       'movie_imdb_link', 'num_user_for_reviews', 'language', 'country',
       'content_rating', 'budget', 'title_year', 'actor_2_facebook_likes',
       'imdb_score', 'aspect_ratio', 'movie_facebook_likes', 'profit'],
      dtype='object')

In [ ]:
top10 = # Write your code to get the top 10 profiting movies here

**Checkpoint:** You might spot two movies directed by `James Cameron` in the list.

#### <font color='red'>Question 6: Which movie is ranked 5th from the top in the list obtained? </font>
-  <font color='red'>E.T. the Extra-Terrestrial</font>
-  <font color='red'>The Avengers</font>
-  <font color='red'>The Dark Knight</font>
-  <font color='red'>Titanic</font>

In [34]:
# Write your code for sorting the dataframe here
movies_sorted  = movies.sort_values('profit', ascending = False)
fifth_highest_movie = movies_sorted.iloc[4]['movie_title']  # Get the 5th highest movie title (index 4)
print(fifth_highest_movie)

E.T. the Extra-Terrestrial

**Subtask 3.3: Find IMDb Top 250**

Create a new dataframe `IMDb_Top_250` and store the top 250 movies with the highest IMDb Rating (corresponding to the column: `imdb_score`). Also make sure that for all of these movies, the `num_voted_users` is greater than 25,000. 

Also add a `Rank` column containing the values 1 to 250 indicating the ranks of the corresponding films.

In [35]:
# Write your code for extracting the top 250 movies as per the IMDb score here. Make sure that you store it in a new dataframe 
# and name that dataframe as 'IMDb_Top_250'
import pandas as pd

# Filter movies with num_voted_users > 25,000
filtered_movies = movies[movies["num_voted_users"] > 25000]

# Select the top 250 movies with the highest IMDb score
IMDb_Top_250 = filtered_movies.sort_values("imdb_score", ascending=False).head(250)

# Add a Rank column
IMDb_Top_250["Rank"] = range(1, 251)

# Display the top 5 rows
print(IMDb_Top_250.head())

      color         director_name  num_critic_for_reviews  duration  \
1795  Color        Frank Darabont                   199.0     142.0
3016  Color  Francis Ford Coppola                   208.0     175.0
64    Color     Christopher Nolan                   645.0     152.0
2543  Color  Francis Ford Coppola                   149.0     220.0
325   Color         Peter Jackson                   328.0     192.0

      director_facebook_likes  actor_3_facebook_likes    actor_2_name  \
1795                      0.0                   461.0  Jeffrey DeMunn
3016                      0.0                  3000.0   Marlon Brando
64                    22000.0                 11000.0    Heath Ledger
2543                      0.0                  3000.0       Al Pacino
325                       0.0                   416.0      Billy Boyd

      actor_1_facebook_likes       gross                          genres  ...  \
1795                 11000.0   28.341469                     Crime|Drama  ...
3016                 14000.0  134.821952                     Crime|Drama  ...
64                   23000.0  533.316061     Action|Crime|Drama|Thriller  ...
2543                 22000.0   57.300000                     Crime|Drama  ...
325                   5000.0  377.019252  Action|Adventure|Drama|Fantasy  ...

     country content_rating  budget  title_year actor_2_facebook_likes  \
1795     USA              R    25.0      1994.0                  745.0
3016     USA              R     6.0      1972.0                10000.0
64       USA          PG-13   185.0      2008.0                13000.0
2543     USA              R    13.0      1974.0                14000.0
325      USA          PG-13    94.0      2003.0                  857.0

      imdb_score aspect_ratio movie_facebook_likes      profit Rank
1795         9.3         1.85               108000    3.341469    1
3016         9.2         1.85                43000  128.821952    2
64           9.0         2.35                37000  348.316061    3
2543         9.0         1.85                14000   44.300000    4
325          8.9         2.35                16000  283.019252    5

[5 rows x 30 columns]

#### <font color='red'>Question 7: Suppose movies are divided into 5 buckets based on the IMDb ratings: </font>
-  <font color='red'>7.5 to 8</font>
-  <font color='red'>8 to 8.5</font>
-  <font color='red'>8.5 to 9</font>
-  <font color='red'>9 to 9.5</font>
-  <font color='red'>9.5 to 10</font>

<font color = 'red'> Which bucket holds the maximum number of movies from *IMDb_Top_250*? </font>

In [36]:
import pandas as pd

# Define the IMDb rating buckets
bins = [7.5, 8, 8.5, 9, 9.5, 10]
labels = ["[7.5, 8)", "[8, 8.5)", "[8.5, 9)", "[9, 9.5)", "[9.5, 10)"]

# Categorize movies into bins
IMDb_Top_250["Rating_Bucket"] = pd.cut(IMDb_Top_250["imdb_score"], bins=bins, labels=labels, right=False)

# Count movies in each bucket
bucket_counts = IMDb_Top_250["Rating_Bucket"].value_counts()

# Print the bucket with the maximum number of movies
max_bucket = bucket_counts.idxmax()
max_count = bucket_counts.max()

print(f"The bucket {max_bucket} holds the maximum number of movies with a count of {max_count}.")

The bucket [8, 8.5) holds the maximum number of movies with a count of 159.

**Subtask 3.4: Find the critic-favorite and audience-favorite actors**

   1. Create three new dataframes namely, `Meryl_Streep`, `Leo_Caprio`, and `Brad_Pitt` which contain the movies in which the actors: 'Meryl Streep', 'Leonardo DiCaprio', and 'Brad Pitt' are the lead actors. Use only the `actor_1_name` column for extraction. Also, make sure that you use the names 'Meryl Streep', 'Leonardo DiCaprio', and 'Brad Pitt' for the said extraction.
   2. Append the rows of all these dataframes and store them in a new dataframe named `Combined`.
   3. Group the combined dataframe using the `actor_1_name` column.
   4. Find the mean of the `num_critic_for_reviews` and `num_user_for_review` and identify the actors which have the highest mean.

In [37]:
# Write your code for creating three new dataframes here
Meryl_Streep = movies[movies["actor_1_name"] == "Meryl Streep"] # Include all movies in which Meryl_Streep is the lead

In [38]:
Leo_Caprio = movies[movies["actor_1_name"] == "Leonardo DiCaprio"] # Include all movies in which Leo_Caprio is the lead

In [40]:
Brad_Pitt = movies[movies["actor_1_name"] == "Brad Pitt"] # Include all movies in which Brad_Pitt is the lead

In [41]:
print("Meryl Streep Movies:\n", Meryl_Streep)
print("Leonardo DiCaprio Movies:\n", Leo_Caprio)
print("Brad Pitt Movies:\n", Brad_Pitt)

Meryl Streep Movies:
       color   director_name  num_critic_for_reviews  duration  \
392   Color    Nancy Meyers                   187.0     120.0
1038  Color   Curtis Hanson                    42.0     111.0
1132  Color     Nora Ephron                   252.0     123.0
1322  Color   David Frankel                   208.0     109.0
1390  Color  Robert Redford                   227.0      92.0
1471  Color  Sydney Pollack                    66.0     161.0
1514  Color   David Frankel                   234.0     100.0
1563  Color   Carl Franklin                    64.0     127.0
1784  Color  Stephen Daldry                   174.0     114.0
2500  Color  Phyllida Lloyd                   331.0     105.0
2793  Color   Robert Altman                   211.0     105.0

      director_facebook_likes  actor_3_facebook_likes       actor_2_name  \
392                     278.0                   963.0     Hunter Parrish
1038                    161.0                   132.0    Glenn Morshower
1132                      0.0                   923.0  Mary Lynn Rajskub
1322                     64.0                   505.0      Anne Hathaway
1390                      0.0                 10000.0         Tom Cruise
1471                    521.0                   184.0      Michael Gough
1514                     64.0                   329.0       Steve Carell
1563                     73.0                   433.0       William Hurt
1784                    335.0                   530.0    Stephen Dillane
2500                     58.0                   583.0      Jim Broadbent
2793                    500.0                   718.0    Virginia Madsen

      actor_1_facebook_likes       gross                           genres  \
392                  11000.0  112.703470             Comedy|Drama|Romance
1038                 11000.0   46.815748  Action|Adventure|Crime|Thriller
1132                 11000.0   94.125426          Biography|Drama|Romance
1322                 11000.0  124.732962             Comedy|Drama|Romance
1390                 11000.0   14.998070               Drama|Thriller|War
1471                 11000.0   87.100000          Biography|Drama|Romance
1514                 11000.0   63.536011             Comedy|Drama|Romance
1563                 11000.0   23.209440                            Drama
1784                 11000.0   41.597830                    Drama|Romance
2500                 11000.0   29.959436          Biography|Drama|History
2793                 11000.0   20.338609               Comedy|Drama|Music

      ... language country  content_rating  budget title_year  \
392   ...  English     USA               R    85.0     2009.0
1038  ...  English     USA           PG-13    45.0     1994.0
1132  ...  English     USA           PG-13    40.0     2009.0
1322  ...  English     USA           PG-13    35.0     2006.0
1390  ...  English     USA               R    35.0     2007.0
1471  ...  English     USA              PG    31.0     1985.0
1514  ...  English     USA           PG-13    30.0     2012.0
1563  ...  English     USA               R    30.0     1998.0
1784  ...  English     USA           PG-13    25.0     2002.0
2500  ...  English      UK           PG-13    13.0     2011.0
2793  ...  English     USA           PG-13    10.0     2006.0

      actor_2_facebook_likes imdb_score aspect_ratio  movie_facebook_likes  \
392                   2000.0        6.6         1.85                     0
1038                   894.0        6.3         2.35                     0
1132                   935.0        7.0         1.85                 13000
1322                 11000.0        6.8         2.35                     0
1390                 10000.0        6.2         2.35                     0
1471                   920.0        7.2         1.85                     0
1514                  7000.0        6.3         2.35                     0
1563                   882.0        7.0         1.85                   592
1784                   577.0        7.6         1.85                     0
2500                  1000.0        6.4         2.35                 18000
2793                   912.0        6.8         2.35                   683

         profit
392   27.703470
1038   1.815748
1132  54.125426
1322  89.732962
1390 -20.001930
1471  56.100000
1514  33.536011
1563  -6.790560
1784  16.597830
2500  16.959436
2793  10.338609

[11 rows x 29 columns]
Leonardo DiCaprio Movies:
                  color          director_name  num_critic_for_reviews  \
25               Color          James Cameron                   315.0
49               Color           Baz Luhrmann                   490.0
94               Color      Christopher Nolan                   642.0
173              Color  Alejandro G. Iñárritu                   556.0
246    Black and White        Martin Scorsese                   267.0
283              Color      Quentin Tarantino                   765.0
293              Color           Edward Zwick                   166.0
294              Color        Martin Scorsese                   606.0
312              Color        Martin Scorsese                   233.0
347              Color        Martin Scorsese                   352.0
431              Color        Martin Scorsese                   490.0
608              Color           Ridley Scott                   238.0
859              Color       Steven Spielberg                   194.0
934              Color            Danny Boyle                   118.0
1046             Color             Sam Mendes                   323.0
1336             Color        Randall Wallace                    83.0
1364             Color         Clint Eastwood                   392.0
1457   Black and White              Sam Raimi                    63.0
1909             Color             Jerry Zaks                    45.0
2484             Color           Baz Luhrmann                   106.0
3025             Color           Baz Luhrmann                   490.0

      duration  director_facebook_likes  actor_3_facebook_likes  \
25       194.0                      0.0                   794.0
49       143.0                   1000.0                    77.0
94       148.0                  22000.0                 23000.0
173      156.0                      0.0                   733.0
246      170.0                  17000.0                   827.0
283      165.0                  16000.0                   265.0
293      143.0                    380.0                   452.0
294      240.0                  17000.0                  4000.0
312      216.0                  17000.0                  1000.0
347      151.0                  17000.0                  1000.0
431      138.0                  17000.0                   163.0
608      128.0                      0.0                   135.0
859      141.0                  14000.0                  3000.0
934      119.0                      0.0                    39.0
1046     119.0                      0.0                 10000.0
1336     132.0                    130.0                    80.0
1364     137.0                  16000.0                   363.0
1457     107.0                      0.0                   159.0
1909      98.0                      4.0                 11000.0
2484     120.0                   1000.0                   954.0
3025     143.0                   1000.0                    76.0

             actor_2_name  actor_1_facebook_likes       gross  \
25           Kate Winslet                 29000.0  658.672302
49      Elizabeth Debicki                 29000.0  144.812796
94              Tom Hardy                 29000.0  292.568851
173             Tom Hardy                 29000.0  183.635922
246            Adam Scott                 29000.0  102.608827
283       Christoph Waltz                 29000.0  162.804648
293        Djimon Hounsou                 29000.0   57.366262
294   Matthew McConaughey                 29000.0  116.866727
312           Liam Neeson                 29000.0   77.679638
347            Matt Damon                 29000.0  132.373442
431         Joseph Sikora                 29000.0  127.968405
608        Simon McBurney                 29000.0   39.380442
859             Tom Hanks                 29000.0  164.435221
934      Virginie Ledoyen                 29000.0   39.778599
1046         Kate Winslet                 29000.0   22.877808
1336       Anne Parillaud                 29000.0   56.876365
1364          Naomi Watts                 29000.0   37.304950
1457           Pat Hingle                 29000.0   18.636537
1909       Robert De Niro                 29000.0   12.782508
2484     Harold Perrineau                 29000.0   46.338728
3025    Elizabeth Debicki                 29000.0  144.812796

                                genres  ... language    country  \
25                       Drama|Romance  ...  English        USA
49                       Drama|Romance  ...  English  Australia
94    Action|Adventure|Sci-Fi|Thriller  ...  English        USA
173   Adventure|Drama|Thriller|Western  ...  English        USA
246                    Biography|Drama  ...  English        USA
283                      Drama|Western  ...  English        USA
293           Adventure|Drama|Thriller  ...  English    Germany
294       Biography|Comedy|Crime|Drama  ...  English        USA
312                        Crime|Drama  ...  English        USA
347               Crime|Drama|Thriller  ...  English        USA
431                   Mystery|Thriller  ...  English        USA
608              Action|Drama|Thriller  ...  English        USA
859              Biography|Crime|Drama  ...  English        USA
934           Adventure|Drama|Thriller  ...  English        USA
1046                     Drama|Romance  ...  English        USA
1336                  Action|Adventure  ...  English        USA
1364             Biography|Crime|Drama  ...  English        USA
1457           Action|Thriller|Western  ...  English      Japan
1909                             Drama  ...  English        USA
2484                     Drama|Romance  ...  English        USA
3025                     Drama|Romance  ...  English  Australia

      content_rating  budget title_year  actor_2_facebook_likes imdb_score  \
25             PG-13   200.0     1997.0                 14000.0        7.7
49             PG-13   105.0     2013.0                   509.0        7.3
94             PG-13   160.0     2010.0                 27000.0        8.8
173                R   135.0     2015.0                 27000.0        8.1
246            PG-13   110.0     2004.0                  3000.0        7.5
283                R   100.0     2012.0                 11000.0        8.5
293                R   100.0     2006.0                  3000.0        8.0
294                R   100.0     2013.0                 11000.0        8.2
312                R   100.0     2002.0                 14000.0        7.5
347                R    90.0     2006.0                 13000.0        8.5
431                R    80.0     2010.0                   223.0        8.1
608                R    70.0     2008.0                   149.0        7.1
859            PG-13    52.0     2002.0                 15000.0        8.0
934                R    50.0     2000.0                   414.0        6.6
1046               R    35.0     2008.0                 14000.0        7.3
1336           PG-13    35.0     1998.0                   130.0        6.4
1364               R    35.0     2011.0                  6000.0        6.6
1457               R    32.0     1995.0                   165.0        6.4
1909           PG-13    23.0     1996.0                 22000.0        6.7
2484           PG-13    14.5     1996.0                  1000.0        6.8
3025           PG-13   105.0     2013.0                   509.0        7.3

     aspect_ratio  movie_facebook_likes      profit
25           2.35                 26000  458.672302
49           2.35                115000   39.812796
94           2.35                175000  132.568851
173          2.35                190000   48.635922
246          2.35                     0   -7.391173
283          2.35                199000   62.804648
293          2.35                 14000  -42.633738
294          2.35                138000   16.866727
312          2.35                     0  -22.320362
347          2.35                 29000   42.373442
431          2.35                 53000   47.968405
608          2.35                     0  -30.619558
859          1.85                 15000  112.435221
934          2.35                     0  -10.221401
1046         2.35                     0  -12.122192
1336         1.85                     0   21.876365
1364         2.35                 16000    2.304950
1457         1.85                     0  -13.363463
1909         1.85                  1000  -10.217492
2484         2.35                 10000   31.838728
3025         2.35                115000   39.812796

[21 rows x 29 columns]
Brad Pitt Movies:
       color          director_name  num_critic_for_reviews  duration  \
97    Color          David Fincher                   362.0     166.0
142   Color      Wolfgang Petersen                   220.0     196.0
243   Color      Steven Soderbergh                   198.0     125.0
244   Color             Doug Liman                   233.0     126.0
367   Color             Tony Scott                   142.0     114.0
383   Color      Steven Soderbergh                   186.0     116.0
448   Color             David Ayer                   406.0     134.0
579   Color    Jean-Jacques Annaud                    76.0     136.0
646   Color          David Fincher                   315.0     151.0
749   Color        Patrick Gilmore                    98.0      85.0
887   Color            Neil Jordan                   120.0     123.0
1397  Color        Terrence Malick                   584.0     139.0
1608  Color         Andrew Dominik                   273.0     160.0
2030  Color  Alejandro G. Iñárritu                   285.0     143.0
2146  Color    Angelina Jolie Pitt                   131.0     122.0
2428  Color         Andrew Dominik                   414.0      97.0
2602  Color             Tony Scott                   122.0     121.0

      director_facebook_likes  actor_3_facebook_likes         actor_2_name  \
97                    21000.0                   919.0        Jason Flemyng
142                     249.0                   844.0        Orlando Bloom
243                       0.0                   350.0        Julia Roberts
244                     218.0                   322.0  Angelina Jolie Pitt
367                   12000.0                   307.0      Stephen Dillane
383                       0.0                   471.0           Bernie Mac
448                     452.0                   697.0         Logan Lerman
579                     218.0                   400.0                 Mako
646                   21000.0                   637.0            Meat Loaf
749                       0.0                    82.0     Adriano Giannini
887                     277.0                  4000.0           Tom Cruise
1397                      0.0                   687.0         Tye Sheridan
1608                    181.0                   820.0        Jeremy Renner
2030                      0.0                    51.0       Harriet Walter
2146                  11000.0                   188.0  Angelina Jolie Pitt
2428                    181.0                   748.0          Sam Shepard
2602                  12000.0                   975.0          Gary Oldman

      actor_1_facebook_likes       gross  \
97                   11000.0  127.490802
142                  11000.0  133.228348
243                  11000.0  125.531634
244                  11000.0  186.336103
367                  11000.0    0.026871
383                  11000.0  183.405771
448                  11000.0   85.707116
579                  11000.0   37.901509
646                  11000.0   37.023395
749                  11000.0   26.288320
887                  11000.0  105.264608
1397                 11000.0   13.303319
1608                 11000.0    3.904982
2030                 11000.0   34.300771
2146                 11000.0    0.531009
2428                 11000.0   14.938570
2602                 11000.0   12.281500

                                                 genres  ... language  \
97                                Drama|Fantasy|Romance  ...  English
142                                           Adventure  ...  English
243                                      Crime|Thriller  ...  English
244                Action|Comedy|Crime|Romance|Thriller  ...  English
367                               Action|Crime|Thriller  ...  English
383                                      Crime|Thriller  ...  English
448                                    Action|Drama|War  ...  English
579               Adventure|Biography|Drama|History|War  ...  English
646                                               Drama  ...  English
749   Adventure|Animation|Comedy|Drama|Family|Fantas...  ...  English
887                                Drama|Fantasy|Horror  ...  English
1397                                      Drama|Fantasy  ...  English
1608              Biography|Crime|Drama|History|Western  ...  English
2030                                              Drama  ...  English
2146                                      Drama|Romance  ...  English
2428                                     Crime|Thriller  ...  English
2602                Action|Crime|Drama|Romance|Thriller  ...  English

      country  content_rating  budget title_year  actor_2_facebook_likes  \
97        USA           PG-13   150.0     2008.0                  1000.0
142       USA               R   175.0     2004.0                  5000.0
243       USA           PG-13   110.0     2004.0                  8000.0
244       USA           PG-13   120.0     2005.0                 11000.0
367   Germany               R    92.0     2001.0                   577.0
383       USA           PG-13    85.0     2001.0                  1000.0
448       USA               R    68.0     2014.0                  8000.0
579       USA           PG-13    70.0     1997.0                   691.0
646       USA               R    63.0     1999.0                   783.0
749       USA              PG    60.0     2003.0                   102.0
887       USA               R    60.0     1994.0                 10000.0
1397      USA           PG-13    32.0     2011.0                  1000.0
1608      USA               R    30.0     2007.0                 10000.0
2030   France               R    25.0     2006.0                   119.0
2146      USA               R    10.0     2015.0                 11000.0
2428      USA               R    15.0     2012.0                   820.0
2602      USA               R    13.0     1993.0                 10000.0

     imdb_score aspect_ratio  movie_facebook_likes     profit
97          7.8         2.35                 23000 -22.509198
142         7.2         2.35                     0 -41.771652
243         6.4         2.35                     0  15.531634
244         6.5         2.35                     0  66.336103
367         7.0         2.35                     0 -91.973129
383         7.8         2.35                     0  98.405771
448         7.6         2.35                 82000  17.707116
579         7.0         2.35                     0 -32.098491
646         8.8         2.35                 48000 -25.976605
749         6.7         1.66                   880 -33.711680
887         7.6         1.85                 11000  45.264608
1397        6.7         1.85                 39000 -18.696681
1608        7.5         2.35                     0 -26.095018
2030        7.5         1.85                     0   9.300771
2146        5.3         2.35                     0  -9.468991
2428        6.2         2.35                 20000  -0.061430

In [42]:
# Write your code for combining the three dataframes here
# Combine the three DataFrames into one
combined_df = pd.concat([Meryl_Streep, Leo_Caprio, Brad_Pitt], ignore_index=True)

# Display the combined DataFrame
print(combined_df)

               color          director_name  num_critic_for_reviews  duration  \
0              Color           Nancy Meyers                   187.0     120.0
1              Color          Curtis Hanson                    42.0     111.0
2              Color            Nora Ephron                   252.0     123.0
3              Color          David Frankel                   208.0     109.0
4              Color         Robert Redford                   227.0      92.0
5              Color         Sydney Pollack                    66.0     161.0
6              Color          David Frankel                   234.0     100.0
7              Color          Carl Franklin                    64.0     127.0
8              Color         Stephen Daldry                   174.0     114.0
9              Color         Phyllida Lloyd                   331.0     105.0
10             Color          Robert Altman                   211.0     105.0
11             Color          James Cameron                   315.0     194.0
12             Color           Baz Luhrmann                   490.0     143.0
13             Color      Christopher Nolan                   642.0     148.0
14             Color  Alejandro G. Iñárritu                   556.0     156.0
15   Black and White        Martin Scorsese                   267.0     170.0
16             Color      Quentin Tarantino                   765.0     165.0
17             Color           Edward Zwick                   166.0     143.0
18             Color        Martin Scorsese                   606.0     240.0
19             Color        Martin Scorsese                   233.0     216.0
20             Color        Martin Scorsese                   352.0     151.0
21             Color        Martin Scorsese                   490.0     138.0
22             Color           Ridley Scott                   238.0     128.0
23             Color       Steven Spielberg                   194.0     141.0
24             Color            Danny Boyle                   118.0     119.0
25             Color             Sam Mendes                   323.0     119.0
26             Color        Randall Wallace                    83.0     132.0
27             Color         Clint Eastwood                   392.0     137.0
28   Black and White              Sam Raimi                    63.0     107.0
29             Color             Jerry Zaks                    45.0      98.0
30             Color           Baz Luhrmann                   106.0     120.0
31             Color           Baz Luhrmann                   490.0     143.0
32             Color          David Fincher                   362.0     166.0
33             Color      Wolfgang Petersen                   220.0     196.0
34             Color      Steven Soderbergh                   198.0     125.0
35             Color             Doug Liman                   233.0     126.0
36             Color             Tony Scott                   142.0     114.0
37             Color      Steven Soderbergh                   186.0     116.0
38             Color             David Ayer                   406.0     134.0
39             Color    Jean-Jacques Annaud                    76.0     136.0
40             Color          David Fincher                   315.0     151.0
41             Color        Patrick Gilmore                    98.0      85.0
42             Color            Neil Jordan                   120.0     123.0
43             Color        Terrence Malick                   584.0     139.0
44             Color         Andrew Dominik                   273.0     160.0
45             Color  Alejandro G. Iñárritu                   285.0     143.0
46             Color    Angelina Jolie Pitt                   131.0     122.0
47             Color         Andrew Dominik                   414.0      97.0
48             Color             Tony Scott                   122.0     121.0

    director_facebook_likes  actor_3_facebook_likes         actor_2_name  \
0                     278.0                   963.0       Hunter Parrish
1                     161.0                   132.0      Glenn Morshower
2                       0.0                   923.0    Mary Lynn Rajskub
3                      64.0                   505.0        Anne Hathaway
4                       0.0                 10000.0           Tom Cruise
5                     521.0                   184.0        Michael Gough
6                      64.0                   329.0         Steve Carell
7                      73.0                   433.0         William Hurt
8                     335.0                   530.0      Stephen Dillane
9                      58.0                   583.0        Jim Broadbent
10                    500.0                   718.0      Virginia Madsen
11                      0.0                   794.0         Kate Winslet
12                   1000.0                    77.0    Elizabeth Debicki
13                  22000.0                 23000.0            Tom Hardy
14                      0.0                   733.0            Tom Hardy
15                  17000.0                   827.0           Adam Scott
16                  16000.0                   265.0      Christoph Waltz
17                    380.0                   452.0       Djimon Hounsou
18                  17000.0                  4000.0  Matthew McConaughey
19                  17000.0                  1000.0          Liam Neeson
20                  17000.0                  1000.0           Matt Damon
21                  17000.0                   163.0        Joseph Sikora
22                      0.0                   135.0       Simon McBurney
23                  14000.0                  3000.0            Tom Hanks
24                      0.0                    39.0     Virginie Ledoyen
25                      0.0                 10000.0         Kate Winslet
26                    130.0                    80.0       Anne Parillaud
27                  16000.0                   363.0          Naomi Watts
28                      0.0                   159.0           Pat Hingle
29                      4.0                 11000.0       Robert De Niro
30                   1000.0                   954.0     Harold Perrineau
31                   1000.0                    76.0    Elizabeth Debicki
32                  21000.0                   919.0        Jason Flemyng
33                    249.0                   844.0        Orlando Bloom
34                      0.0                   350.0        Julia Roberts
35                    218.0                   322.0  Angelina Jolie Pitt
36                  12000.0                   307.0      Stephen Dillane
37                      0.0                   471.0           Bernie Mac
38                    452.0                   697.0         Logan Lerman
39                    218.0                   400.0                 Mako
40                  21000.0                   637.0            Meat Loaf
41                      0.0                    82.0     Adriano Giannini
42                    277.0                  4000.0           Tom Cruise
43                      0.0                   687.0         Tye Sheridan
44                    181.0                   820.0        Jeremy Renner
45                      0.0                    51.0       Harriet Walter
46                  11000.0                   188.0  Angelina Jolie Pitt
47                    181.0                   748.0          Sam Shepard
48                  12000.0                   975.0          Gary Oldman

    actor_1_facebook_likes       gross  \
0                  11000.0  112.703470
1                  11000.0   46.815748
2                  11000.0   94.125426
3                  11000.0  124.732962
4                  11000.0   14.998070
5                  11000.0   87.100000
6                  11000.0   63.536011
7                  11000.0   23.209440
8                  11000.0   41.597830
9                  11000.0   29.959436
10                 11000.0   20.338609
11                 29000.0  658.672302
12                 29000.0  144.812796
13                 29000.0  292.568851
14                 29000.0  183.635922
15                 29000.0  102.608827
16                 29000.0  162.804648
17                 29000.0   57.366262
18                 29000.0  116.866727
19                 29000.0   77.679638
20                 29000.0  132.373442
21                 29000.0  127.968405
22                 29000.0   39.380442
23                 29000.0  164.435221
24                 29000.0   39.778599
25                 29000.0   22.877808
26                 29000.0   56.876365
27                 29000.0   37.304950
28                 29000.0   18.636537
29                 29000.0   12.782508
30                 29000.0   46.338728
31                 29000.0  144.812796
32                 11000.0  127.490802
33                 11000.0  133.228348
34                 11000.0  125.531634
35                 11000.0  186.336103
36                 11000.0    0.026871
37                 11000.0  183.405771
38                 11000.0   85.707116
39                 11000.0   37.901509
40                 11000.0   37.023395
41                 11000.0   26.288320
42                 11000.0  105.264608
43                 11000.0   13.303319
44                 11000.0    3.904982
45                 11000.0   34.300771
46                 11000.0    0.531009
47                 11000.0   14.938570
48                 11000.0   12.281500

                                               genres  ... language  \
0                                Comedy|Drama|Romance  ...  English
1                     Action|Adventure|Crime|Thriller  ...  English
2                             Biography|Drama|Romance  ...  English
3                                Comedy|Drama|Romance  ...  English
4                                  Drama|Thriller|War  ...  English
5                             Biography|Drama|Romance  ...  English
6                                Comedy|Drama|Romance  ...  English
7                                               Drama  ...  English
8                                       Drama|Romance  ...  English
9                             Biography|Drama|History  ...  English
10                                 Comedy|Drama|Music  ...  English
11                                      Drama|Romance  ...  English
12                                      Drama|Romance  ...  English
13                   Action|Adventure|Sci-Fi|Thriller  ...  English
14                   Adventure|Drama|Thriller|Western  ...  English
15                                    Biography|Drama  ...  English
16                                      Drama|Western  ...  English
17                           Adventure|Drama|Thriller  ...  English
18                       Biography|Comedy|Crime|Drama  ...  English
19                                        Crime|Drama  ...  English
20                               Crime|Drama|Thriller  ...  English
21                                   Mystery|Thriller  ...  English
22                              Action|Drama|Thriller  ...  English
23                              Biography|Crime|Drama  ...  English
24                           Adventure|Drama|Thriller  ...  English
25                                      Drama|Romance  ...  English
26                                   Action|Adventure  ...  English
27                              Biography|Crime|Drama  ...  English
28                            Action|Thriller|Western  ...  English
29                                              Drama  ...  English
30                                      Drama|Romance  ...  English
31                                      Drama|Romance  ...  English
32                              Drama|Fantasy|Romance  ...  English
33                                          Adventure  ...  English
34                                     Crime|Thriller  ...  English
35               Action|Comedy|Crime|Romance|Thriller  ...  English
36                              Action|Crime|Thriller  ...  English
37                                     Crime|Thriller  ...  English
38                                   Action|Drama|War  ...  English
39              Adventure|Biography|Drama|History|War  ...  English
40                                              Drama  ...  English
41  Adventure|Animation|Comedy|Drama|Family|Fantas...  ...  English
42                               Drama|Fantasy|Horror  ...  English
43                                      Drama|Fantasy  ...  English
44              Biography|Crime|Drama|History|Western  ...  English
45                                              Drama  ...  English
46                                      Drama|Romance  ...  English
47                                     Crime|Thriller  ...  English
48                Action|Crime|Drama|Romance|Thriller  ...  English

      country  content_rating  budget title_year  actor_2_facebook_likes  \
0         USA               R    85.0     2009.0                  2000.0
1         USA           PG-13    45.0     1994.0                   894.0
2         USA           PG-13    40.0     2009.0                   935.0
3         USA           PG-13    35.0     2006.0                 11000.0
4         USA               R    35.0     2007.0                 10000.0
5         USA              PG    31.0     1985.0                   920.0
6         USA           PG-13    30.0     2012.0                  7000.0
7         USA               R    30.0     1998.0                   882.0
8         USA           PG-13    25.0     2002.0                   577.0
9          UK           PG-13    13.0     2011.0                  1000.0
10        USA           PG-13    10.0     2006.0                   912.0
11        USA           PG-13   200.0     1997.0                 14000.0
12  Australia           PG-13   105.0     2013.0                   509.0
13        USA           PG-13   160.0     2010.0                 27000.0
14        USA               R   135.0     2015.0                 27000.0
15        USA           PG-13   110.0     2004.0                  3000.0
16        USA               R   100.0     2012.0                 11000.0
17    Germany               R   100.0     2006.0                  3000.0
18        USA               R   100.0     2013.0                 11000.0
19        USA               R   100.0     2002.0                 14000.0
20        USA               R    90.0     2006.0                 13000.0
21        USA               R    80.0     2010.0                   223.0
22        USA               R    70.0     2008.0                   149.0
23        USA           PG-13    52.0     2002.0                 15000.0
24        USA               R    50.0     2000.0                   414.0
25        USA               R    35.0     2008.0                 14000.0
26        USA           PG-13    35.0     1998.0                   130.0
27        USA               R    35.0     2011.0                  6000.0
28      Japan               R    32.0     1995.0                   165.0
29        USA           PG-13    23.0     1996.0                 22000.0
30        USA           PG-13    14.5     1996.0                  1000.0
31  Australia           PG-13   105.0     2013.0                   509.0
32        USA           PG-13   150.0     2008.0                  1000.0
33        USA               R   175.0     2004.0                  5000.0
34        USA           PG-13   110.0     2004.0                  8000.0
35        USA           PG-13   120.0     2005.0                 11000.0
36    Germany               R    92.0     2001.0                   577.0
37        USA           PG-13    85.0     2001.0                  1000.0
38        USA               R    68.0     2014.0                  8000.0
39        USA           PG-13    70.0     1997.0                   691.0
40        USA               R    63.0     1999.0                   783.0
41        USA              PG    60.0     2003.0                   102.0
42        USA               R    60.0     1994.0                 10000.0
43        USA           PG-13    32.0     2011.0                  1000.0
44        USA               R    30.0     2007.0                 10000.0
45     France               R    25.0     2006.0                   119.0
46        USA               R    10.0     2015.0                 11000.0
47        USA               R    15.0     2012.0                   820.0
48        USA               R    13.0     1993.0                 10000.0

   imdb_score aspect_ratio  movie_facebook_likes      profit
0         6.6         1.85                     0   27.703470
1         6.3         2.35                     0    1.815748
2         7.0         1.85                 13000   54.125426
3         6.8         2.35                     0   89.732962
4         6.2         2.35                     0  -20.001930
5         7.2         1.85                     0   56.100000
6         6.3         2.35                     0   33.536011
7         7.0         1.85                   592   -6.790560
8         7.6         1.85                     0   16.597830
9         6.4         2.35                 18000   16.959436
10        6.8         2.35                   683   10.338609
11        7.7         2.35                 26000  458.672302
12        7.3         2.35                115000   39.812796
13        8.8         2.35                175000  132.568851
14        8.1         2.35                190000   48.635922
15        7.5         2.35                     0   -7.391173
16        8.5         2.35                199000   62.804648
17        8.0         2.35                 14000  -42.633738
18        8.2         2.35                138000   16.866727
19        7.5         2.35                     0  -22.320362
20        8.5         2.35                 29000   42.373442
21        8.1         2.35                 53000   47.968405
22        7.1         2.35                     0  -30.619558
23        8.0         1.85                 15000  112.435221
24        6.6         2.35                     0  -10.221401
25        7.3         2.35                     0  -12.122192
26        6.4         1.85                     0   21.876365
27        6.6         2.35                 16000    2.304950
28        6.4         1.85                     0  -13.363463
29        6.7         1.85                  1000  -10.217492
30        6.8         2.35                 10000   31.838728
31        7.3         2.35                115000   39.812796
32        7.8         2.35                 23000  -22.509198
33        7.2         2.35                     0  -41.771652
34        6.4         2.35                     0   15.531634
35        6.5         2.35                     0   66.336103
36        7.0         2.35                     0  -91.973129
37        7.8         2.35                     0   98.405771
38        7.6         2.35                 82000   17.707116
39        7.0         2.35                     0  -32.098491
40        8.8         2.35                 48000  -25.976605
41        6.7         1.66                   880  -33.711680
42        7.6         1.85                 11000   45.264608
43        6.7         1.85                 39000  -18.696681
44        7.5         2.35                     0  -26.095018
45        7.5         1.85                     0    9.300771
46        5.3         2.35                     0   -9.468991
47        6.2         2.35                 20000   -0.061430
48        8.0         2.35                 15000   -0.718500

[49 rows x 29 columns]

In [47]:
# Write your code for grouping the combined dataframe here

# Group by actor name and calculate mean for num_critic_for_reviews and duration
grouped_mean_df = combined_df.groupby("actor_1_name")[["num_critic_for_reviews", "duration"]].mean().reset_index()

# Sort by num_critic_for_reviews in descending order
sorted_df = grouped_mean_df.sort_values(by="num_critic_for_reviews", ascending=False)

# Display the sorted DataFrame
print(sorted_df)

        actor_1_name  num_critic_for_reviews    duration
1  Leonardo DiCaprio              330.190476  148.000000
0          Brad Pitt              245.000000  132.588235
2       Meryl Streep              181.454545  115.181818

In [49]:
# Write the code for finding the mean of critic reviews and audience reviews here
# Group by actor_1_name and calculate the mean of num_critic_for_reviews and num_user_for_reviews
grouped_mean_df = combined_df.groupby("actor_1_name")[["num_critic_for_reviews", "num_user_for_reviews"]].mean()

# Display the result
print(grouped_mean_df)

                   num_critic_for_reviews  num_user_for_reviews
actor_1_name
Brad Pitt                      245.000000            742.352941
Leonardo DiCaprio              330.190476            914.476190
Meryl Streep                   181.454545            297.181818

#### <font color='red'>Question 8: Which actor is highest rated among the three actors according to the user reviews? </font>
-  <font color='red'>Meryl Streep</font>
-  <font color='red'>Leonardo DiCaprio</font>
-  <font color='red'>Brad Pitt</font>

#### <font color='red'>Question 9: Which actor is highest rated among the three actors according to the critics?</font>
-  <font color='red'>Meryl Streep</font>
-  <font color='red'>Leonardo DiCaprio</font>
-  <font color='red'>Brad Pitt</font>

In [ ]:
# There are two columns 'actor_1_facebook_likes' and 'actor_2_facebook_likes' which have quite a few missing values but since you have 
# less data points, you don't want to drop many of them. For a hypothetical analysis that you're conducting, it will be okay if one of 
# them has a missing value but you can't afford to have both missing values. So your aim here is to find the indices of the rows in which 
# both of these columns have missing values simultaneously.
#Expected Output:
#- First print the indices of the rows where both these columns have missing values. The print statement has been provided in the stub. You just need to fill it. 
#- After you have printed the above indices, drop these particular rows and print the number of retained rows in the dataframe.
# Importing the pandas package

import pandas as pd 

# Reading the dataframe
movies = pd.read_csv('https://query.data.world/s/lqdline2c7rnci4bf4dwjsok6d26jd')

# Print out the indices of the rows in which both these columns have missing values
# as a list
#print(list(# Write your code here))

# Find the indices where both columns have missing values
missing_indices = movies[(movies["actor_1_facebook_likes"].isna()) & (movies["actor_2_facebook_likes"].isna())].index

# Find out the indices of the rows in which both these columns have missing values

missing_indices = movies[(movies["actor_1_facebook_likes"].isna()) & (movies["actor_2_facebook_likes"].isna())].index
print(list(missing_indices))


# Drop these rows
movies = movies.drop(index=missing_indices)

# Print the number of remaining rows
print(movies.shape[0])

In [51]:
# Renaming the column in Initcap
# Importing the pandas package
import pandas as pd

# Reading the dataframe
df = pd.read_csv('https://kh-prod-codelabs.s3.ap-south-1.amazonaws.com/heart-2c1d619e8c1a4e8087742a43948e2cf2.csv')

# Capitalizing the Column name
df.columns = df.columns.str.capitalize()

# Printing the final columns. Do not edit this part.
print(df.columns)

Index(['Age', 'Sex', 'Cp', 'Trestbps', 'Chol', 'Fbs', 'Restecg', 'Thalach',
       'Exang', 'Oldpeak', 'Slope', 'Ca', 'Thal', 'Target'],
      dtype='object')

In [53]:
#There are a lot of columns that aren't visible. But you might have noticed straight away that there are quite a few missing values in the data frame. 
#Two columns for instance, 'aspect_ratio' and 'facenumber_in_poster' also have a few missing values(NaN). Now, replace the missing values with the 
#'median' value of the respective columns and print the null value count for both.
#Expected Output: First print the number of missing values in both of these columns, then output the median in both the columns and then impute the 
#missing values with the respective medians and print the count of missing values again. Store all of these in a dictionary format like the following:
#{'aspect_ratio_mv': 431, 'facenumber_in_poster_mv': 97}
#{'aspect_ratio_median: 1.44, 'facenumber_in_poster': 2.0}
#{'aspect_ratio_final': 0, 'facenumber_in_poster_final': 0}

# Importing the pandas package
import pandas as pd 

# Reading the movies dataframe
movies = pd.read_csv('https://query.data.world/s/zlr77ctyxez3kv6zqn6nn5six42cfq')

# Your aim is to complete the following three print statements after all the colons

# Get the null value counts in both the columns
aspect_ratio_mv = movies['aspect_ratio'].isnull().sum()
facenumber_in_poster_mv = movies['facenumber_in_poster'].isnull().sum()

# Complete the first dictionary
mv = {'aspect_ratio_mv': aspect_ratio_mv, 'facenumber_in_poster_mv': facenumber_in_poster_mv}

# Get the median of both the columns
aspect_ratio_median = movies['aspect_ratio'].median()
facenumber_in_poster_median = movies['facenumber_in_poster'].median()

# Complete the second dictionary
median = {'aspect_ratio_median': aspect_ratio_median, 'facenumber_in_poster_median': facenumber_in_poster_median}

movies.loc[pd.isnull(movies['aspect_ratio']), ['aspect_ratio']] = movies['aspect_ratio'].median()
movies.loc[pd.isnull(movies['facenumber_in_poster']), ['facenumber_in_poster']] = movies['facenumber_in_poster'].median()

# Get the final null value count of both the columns
aspect_ratio_final = movies['aspect_ratio'].isnull().sum()
facenumber_in_poster_final = movies['facenumber_in_poster'].isnull().sum()

# Complete the third dictionary
final = {'aspect_ratio_final': aspect_ratio_final, 'facenumber_in_poster_final': facenumber_in_poster_final}

# Printing the values in the three dictionaries. Please do not edit this part
print(sorted(mv.values()))
print(sorted(median.values()))
print(sorted(final.values()))

[13, 329]
[1.0, 2.35]
[0, 0]